# Generated by Django 2.2 on 2019-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertimemodel',
            name='hours_taught',
        ),
        migrations.AddField(
            model_name='teachertimemodel',
            name='daily_hours_taught',
            field=models.IntegerField(default=1),
        ),
    ]
